source = ~/.config/hypr/hyprland/keybinds.conf
source = ~/.config/hypr/hyprland/io.conf
source = ~/.config/hypr/hyprland/theme.conf
source = ~/.config/hypr/hyprland/defaults.conf


# monitor=eDP-1,2880x1800@90, 0x0, 1.8, bitdepth, 10, cm, hdr, sdrbrightness, 1.5, sdrsaturation, 1.1
# monitor=eDP-1,2880x1800@90, 0x0, 1.8, bitdepth, 10, cm, srgb
monitor=eDP-1,2880x1800@90, 0x0, 1.8, bitdepth, 10, cm, wide, vrr, 1

layerrule = blur,waybar
xwayland {
  force_zero_scaling = true
  use_nearest_neighbor = true
}


exec-once = uwsm app -- waybar &
exec-once = uwsm app -- wl-paste --watch cliphist store &
exec-once = uwsm app -- /usr/lib/polkit-kde-authentication-agent-1 &
exec-once = uwsm app -- dunst &
exec-once = uwsm app -- /usr/bin/kdeconnectd &

#############################
### ENVIRONMENT VARIABLES ###
#############################

# See https://wiki.hyprland.org/Configuring/Environment-variables/

    
env = GDK_SCALE,2
env = SDL_VIDEODRIVER,wayland
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = AQ_DRM_DEVICES, /dev/dri/card1


##############################
### WINDOWS AND WORKSPACES ###
##############################

# Ignore maximize requests from apps. You'll probably like this.
windowrulev2 = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
